name: Build & Test

on:
  push:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors=nullable /m